### ISSUE TITLE
'train_modelnet.py' seems to infinitely train and overfit model.

### ISSUE THREAD

**Issue by MeltyMakes** [dgriffiths3/pointnet2-tensorflow2#3]
Hello,
I'm not sure if I configured the environment incorrectly or something else, but when I run `train_modelnet.py`, the script runs without ever seeming to stop. If I keyboard interrupt it and view the logs in TensorBoard, it appears that the model severely overfits? I'm not sure if I missed something or if this is intentional behaviour for the test script. Thanks for the help! Please let me know if you need more information.

**Environment**
- Ubuntu 16.04
- nvidia-docker 19.03.5, build 633a0ea838
     - Using tensorflow/tensorflow:latest-devel-gpu
- Python3 3.6.9
- CUDA 10.1
- Tensorflow 2.1.0

**Steps to recreate**
- Create docker instance
    - Mount folder instance
    - Run `compile_ops.sh`
    - Download `tfrecords` for `modelnet`
- Run `train_modelnet.py`

**Output**
```
root@ubuntu:/pointnet# python3 train_modelnet.py 
Model: "cls_ssg__model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
pointnet_sa (Pointnet_SA)    multiple                  12480     
_________________________________________________________________
pointnet_sa_1 (Pointnet_SA)  multiple                  65920     
_________________________________________________________________
pointnet_sa_2 (Pointnet_SA)  multiple                  721664    
_________________________________________________________________
dense (Dense)                multiple                  524800    
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense_1 (Dense)              multiple                  65664     
_________________________________________________________________
dropout_1 (Dropout)          multiple                  0         
_________________________________________________________________
dense_2 (Dense)              multiple                  5160      
=================================================================
Total params: 1,395,688
Trainable params: 1,395,688
Non-trainable params: 0
_________________________________________________________________
None
[info] model training...
^CTraceback (most recent call last):
  File "train_modelnet.py", line 138, in <module>
    train(config, params)
  File "train_modelnet.py", line 90, in train
    train_labels
  File "train_modelnet.py", line 31, in train_step
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 444, in apply_gradients
    kwargs={"name": name})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1949, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1956, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 500, in _distributed_apply
    return self._iterations.assign_add(1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 786, in assign_add
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 44, in assign_add_variable_op
    tld.op_callbacks, resource, value)
KeyboardInterrupt
```
![Selection_001](https://user-images.githubusercontent.com/6192677/73900118-10c68880-48d2-11ea-91f3-ba84262a39eb.png)

**Comment by dgriffiths3** [comment]
This repository does not try to replicate the original, nor is it supposed to be a complete solution for training a PointNet++ model. My idea was more just to share the layers so anyone could make their own PointNet++ like model. The `train_modelnet.py` is more just an example of how you could define a model to train. As such I never added any early stopping, or epoch counts etc..

The overfitting is definitely an issue though, it should just converge and remain generally quite stable. It is extra odd the train curve also decreases. I never actually trained it for this long. I will look into it ASAP.

**Comment by dgriffiths3** [comment]
Should be fixed now we are using callbacks and the `.fit()` function for training.
